

vendor_qti_ims_call_conference_info_start_element
vendor_qti_ims_call_reg_state_update
vendor_qti_ims_call_hangup
vendor_qti_ims_call_send_dtmf
vendor_qti_ims_call_conference
vendor_qti_ims_call_conference_request_complete
vendor_qti_ims_call_swap
vendor_qti_ims_call_result_request_continue
vendor_qti_ims_call_result_request_continue_resume
vendor_qti_ims_call_result_request_continue_answer
vendor_qti_ims_call_answer
vendor_qti_ims_call_dial
vendor_qti_ims_call_handle_conference_info
vendor_qti_ims_call_handle_conf_user_deleted
vendor_qti_ims_call_handle_conf_user_info_changed
vendor_qti_ims_call_handle_state_change
